version: '2'

services:

  plhhoa:
      image: 192.168.1.151:32000/plhhoa:1.0.101
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
