version: '2'

services:

  plhhoa:
      image: neon-registry.4e88-13d3-b83a-9fc9.neoncluster.io/leenet/plhhoa:1.0.125
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
