version: '2'

services:

  plhhoa:
      image: neon-registry.18e7-091a-7bb4-d81e.neoncluster.io/leenet/plhhoa:1.0.125
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
